import type { Component } from 'svelte';
import {
	Antenna,
	Atom,
	Banknote,
	Binary,
	BookOpen,
	Bot,
	Braces,
	Brain,
	BrainCircuit,
	BriefcaseBusiness,
	Brush,
	Bug,
	Cable,
	Calculator,
	Camera,
	ChartColumn,
	ChartPie,
	ChartSpline,
	CircuitBoard,
	Code,
	Coins,
	Cpu,
	Database,
	Dna,
	DraftingCompass,
	Drama,
	Dumbbell,
	Earth,
	Factory,
	Feather,
	FlaskConical,
	Gamepad2,
	Gavel,
	Globe,
	GraduationCap,
	Handshake,
	HeartPulse,
	Infinity as InfinityIcon,
	Languages,
	Leaf,
	Library,
	Lightbulb,
	Lock,
	Magnet,
	Megaphone,
	MessageSquareText,
	Microchip,
	Microscope,
	Monitor,
	Music,
	Network,
	NotebookPen,
	Orbit,
	Palette,
	PenTool,
	Percent,
	Pi,
	Puzzle,
	Radio,
	ReceiptText,
	Rocket,
	Router,
	Satellite,
	Scale,
	ScrollText,
	Server,
	ShieldCheck,
	Sigma,
	Signal,
	Smartphone,
	SquareFunction,
	Target,
	Telescope,
	Terminal,
	TestTubeDiagonal,
	Trophy,
	Users,
	Volleyball,
	Wifi,
	Zap
} from '@lucide/svelte';

type Icon = Component<{ size?: number | string; strokeWidth?: number | string }>;

/**
 * Картинки иконок предметов. Отдельный модуль: его грузит iconLoader после первой отрисовки, чтобы
 * 80 иконок не утяжеляли каждую страницу (см. scripts/bundle-size.mjs).
 */
export const ICONS: Record<string, Icon> = {
	sigma: Sigma,
	function: SquareFunction,
	pi: Pi,
	infinity: InfinityIcon,
	calculator: Calculator,
	percent: Percent,
	'chart-spline': ChartSpline,
	compass: DraftingCompass,
	atom: Atom,
	magnet: Magnet,
	zap: Zap,
	flask: FlaskConical,
	'test-tube': TestTubeDiagonal,
	dna: Dna,
	microscope: Microscope,
	leaf: Leaf,
	earth: Earth,
	telescope: Telescope,
	orbit: Orbit,
	code: Code,
	braces: Braces,
	terminal: Terminal,
	binary: Binary,
	database: Database,
	server: Server,
	cpu: Cpu,
	microchip: Microchip,
	circuit: CircuitBoard,
	network: Network,
	router: Router,
	wifi: Wifi,
	antenna: Antenna,
	radio: Radio,
	signal: Signal,
	satellite: Satellite,
	cable: Cable,
	shield: ShieldCheck,
	lock: Lock,
	bot: Bot,
	'brain-circuit': BrainCircuit,
	globe: Globe,
	monitor: Monitor,
	smartphone: Smartphone,
	bug: Bug,
	languages: Languages,
	feather: Feather,
	book: BookOpen,
	scroll: ScrollText,
	scale: Scale,
	gavel: Gavel,
	brain: Brain,
	users: Users,
	handshake: Handshake,
	message: MessageSquareText,
	lightbulb: Lightbulb,
	drama: Drama,
	library: Library,
	coins: Coins,
	banknote: Banknote,
	receipt: ReceiptText,
	briefcase: BriefcaseBusiness,
	megaphone: Megaphone,
	'chart-column': ChartColumn,
	'chart-pie': ChartPie,
	factory: Factory,
	dumbbell: Dumbbell,
	volleyball: Volleyball,
	'heart-pulse': HeartPulse,
	'pen-tool': PenTool,
	palette: Palette,
	brush: Brush,
	music: Music,
	camera: Camera,
	'graduation-cap': GraduationCap,
	notebook: NotebookPen,
	rocket: Rocket,
	target: Target,
	puzzle: Puzzle,
	trophy: Trophy,
	gamepad: Gamepad2
};
